(function(){function i(a){throw a;}var j=void 0,k=!0,l=null,n=!1;function o(){return function(){}}var p,q=this;function aa(a){for(var a=a.split("."),b=q,c;c=a.shift();)if(b[c]!=l)b=b[c];else return l;return b}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function s(a){return a!==j}function ca(a){return"array"==ba(a)}function v(a){return"string"==typeof a}function w(a){return"function"==ba(a)}var y="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){a||i(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function z(a,b,c){z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return z.apply(l,arguments)}var ga=Date.now||function(){return+new Date};
function B(a,b){var c=a.split("."),d=q;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&s(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function C(a,b){function c(){}c.prototype=b.prototype;a.M=b.prototype;a.prototype=new c};function ha(a){if(!ja.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ka,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(la,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ma,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(na,"&quot;"));return a}var ka=/&/g,la=/</g,ma=/>/g,na=/\"/g,ja=/[&<>\"]/,oa={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},pa={"'":"\\'"};
function F(a){a=String(a);if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=b,g=c+1,h;if(!(h=oa[d])){if(!(31<e&&127>e))if(d in pa)d=pa[d];else if(d in oa)d=pa[d]=oa[d];else{e=d;h=d.charCodeAt(0);if(31<h&&127>h)e=d;else{if(256>h){if(e="\\x",16>h||256<h)e+="0"}else e="\\u",4096>h&&(e+="0");e+=h.toString(16).toUpperCase()}d=pa[d]=e}h=d}f[g]=h}b.push('"');return b.join("")};var G,qa,ra,sa;function ta(){return q.navigator?q.navigator.userAgent:l}sa=ra=qa=G=n;var ua;if(ua=ta()){var va=q.navigator;G=0==ua.indexOf("Opera");qa=!G&&-1!=ua.indexOf("MSIE");ra=!G&&-1!=ua.indexOf("WebKit");sa=!G&&!ra&&"Gecko"==va.product}var wa=G,H=qa,xa=sa,ya=ra,za;
a:{var Aa="",Ba;if(wa&&q.opera)var Ca=q.opera.version,Aa="function"==typeof Ca?Ca():Ca;else if(xa?Ba=/rv\:([^\);]+)(\)|;)/:H?Ba=/MSIE\s+([^\);]+)(\)|;)/:ya&&(Ba=/WebKit\/(\S+)/),Ba)var Da=Ba.exec(ta()),Aa=Da?Da[1]:"";if(H){var Ea,Fa=q.document;Ea=Fa?Fa.documentMode:j;if(Ea>parseFloat(Aa)){za=String(Ea);break a}}za=Aa}var Ga={};
function I(a){var b;if(!(b=Ga[a])){b=0;for(var c=String(za).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",r=/(\d*)(\D*)/g,t=/(\d*)(\D*)/g;do{var u=r.exec(g)||["","",""],m=t.exec(h)||["","",""];if(0==u[0].length&&0==m[0].length)break;b=((0==u[1].length?0:parseInt(u[1],10))<(0==m[1].length?0:parseInt(m[1],10))?-1:(0==u[1].length?0:parseInt(u[1],10))>(0==m[1].length?
0:parseInt(m[1],10))?1:0)||((0==u[2].length)<(0==m[2].length)?-1:(0==u[2].length)>(0==m[2].length)?1:0)||(u[2]<m[2]?-1:u[2]>m[2]?1:0)}while(0==b)}b=Ga[a]=0<=b}return b}var Ha={};function Ia(){return Ha[9]||(Ha[9]=H&&!!document.documentMode&&9<=document.documentMode)};function J(a){Error.captureStackTrace?Error.captureStackTrace(this,J):this.stack=Error().stack||"";a&&(this.message=String(a))}C(J,Error);J.prototype.name="CustomError";var K=Array.prototype,Ja=K.indexOf?function(a,b,c){return K.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(v(a))return!v(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ka=K.forEach?function(a,b,c){K.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},La=K.map?function(a,b,c){return K.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=v(a)?a.split(""):
a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},Ma=K.some?function(a,b,c){return K.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return k;return n};function Na(a,b){var c;a:{c=a.length;for(var d=v(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(j,d[e],e,a)){c=e;break a}c=-1}return 0>c?l:v(a)?a.charAt(c):a[c]};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function L(a,b){this.c=[];this.v=a;this.w=b||l}p=L.prototype;p.m=n;p.s=n;p.t=0;p.D=n;p.N=n;p.C=0;p.cancel=function(a){if(this.m)this.b instanceof L&&this.b.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.C--,0>=b.C&&b.cancel())}this.v?this.v.call(this.w,this):this.D=k;this.m||this.e(new Oa)}};p.F=function(a,b){Pa(this,a,b);this.t--;0==this.t&&this.m&&Qa(this)};function Pa(a,b,c){a.m=k;a.b=c;a.s=!b;Qa(a)}function Ra(a){a.m&&(a.D||i(new Sa),a.D=n)}
p.d=function(a){Ra(this);Pa(this,k,a)};p.e=function(a){Ra(this);Pa(this,n,a)};p.j=function(a,b){return Ta(this,a,l,b)};p.u=function(a,b){return Ta(this,l,a,b)};function Ta(a,b,c,d){a.c.push([b,c,d]);a.m&&Qa(a);return a}function M(a,b){Ta(a,b.d,b.e,b)}function Ua(a){return Ma(a.c,function(a){return w(a[1])})}
function Qa(a){a.l&&(a.m&&Ua(a))&&(q.clearTimeout(a.l),delete a.l);a.a&&(a.a.C--,delete a.a);for(var b=a.b,c=n,d=n;a.c.length&&0==a.t;){var e=a.c.shift(),f=e[0],g=e[1],e=e[2];if(f=a.s?g:f)try{var h=f.call(e||a.w,b);s(h)&&(a.s=a.s&&(h==b||h instanceof Error),a.b=b=h);b instanceof L&&(d=k,a.t++)}catch(r){b=r,a.s=k,Ua(a)||(c=k)}}a.b=b;d&&a.t&&(Ta(b,z(a.F,a,k),z(a.F,a,n)),b.N=k);c&&(a.l=q.setTimeout(function(){i(new Wa(b))},0))}function N(a){var b=new L;b.d(a);return b}
function Xa(a){var b=new L;b.e(a);return b}function Sa(){J.call(this)}C(Sa,J);Sa.prototype.message="Already called";function Oa(){J.call(this)}C(Oa,J);Oa.prototype.message="Deferred was cancelled";function Wa(a){J.call(this);this.message="Unhandled Error in Deferred: "+(a.message||"[No message]")}C(Wa,J);function O(a,b,c,d,e,f){L.call(this,e,f);this.J=a;this.h=[];this.H=!!b;this.S=!!c;this.R=!!d;for(b=0;b<a.length;b++)Ta(a[b],z(this.I,this,b,k),z(this.I,this,b,n));0==a.length&&!this.H&&this.d(this.h)}C(O,L);O.prototype.K=0;O.prototype.I=function(a,b,c){this.K++;this.h[a]=[b,c];this.m||(this.H&&b?this.d([a,c]):this.S&&!b?this.e(c):this.K==this.J.length&&this.d(this.h));this.R&&!b&&(c=l);return c};O.prototype.e=function(a){O.M.e.call(this,a);Ka(this.J,function(a){a.cancel()})};function Ya(a){var b=new L;a.j(function(a){a.every(function(a){return!!a})?b.d(k):b.e(j)});a.u(function(a){b.e(a)});return b};function Za(a,b){this.a=a;this.f=b;this.b=b[b.length-1]}function $a(a,b,c){return"_database_"+a.a+"-"+c+"-"+b}p=Za.prototype;p.put=function(a,b){var c=P(this.b,a),d,e;d=typeof b;if("object"==d&&b!=l||"function"==d)d=ab(b,c.b),d=$a(this,d,a),e=bb(b),window.localStorage.setItem(d,e);else if(ca(b))for(var f=0;f<b.length;f++)d=ab(b[f],c.b),d=$a(this,d,a),e=bb(b),window.localStorage.setItem(d,e);else i(Error("Not object: "+b));return N(k)};
p.get=function(a,b){P(this.b,a);if(s(b)){var c=window.localStorage.getItem($a(this,b,a)),c=c===l?j:cb(c);return N(c)}var d=[],e;for(e in window.localStorage)0==e.lastIndexOf("_database_"+this.a+"-"+a,0)&&(c=window.localStorage[e],d.push(cb(c)));return N(d)};p.clear=function(a){s(a)?a=[a]:(a=this.b,a.b||(a.b=La(a.a,function(a){return a.name})),a=a.b);for(var b in window.localStorage)for(var c,d=0;c=a[d];d++)0==b.lastIndexOf("_database_"+this.a+"-"+c,0)&&delete window.localStorage[b];return N(k)};
p.remove=function(a,b){return s(b)&&s(a)?(delete window.localStorage[$a(this,b,a)],N(k)):this.clear(a)};p.count=function(){var a=new L,b=0,c;for(c in window.localStorage)0==c.lastIndexOf("_database_"+this.a,0)&&b++;a.d(b);return a};p.p=function(){return Xa(k)};!H||Ia();var db=!H||Ia(),eb=H&&!I("8");!ya||I("528");xa&&I("1.9b")||H&&I("8")||wa&&I("9.5")||ya&&I("528");xa&&!I("8")||H&&I("9");function fb(a,b){this.type=a;this.a=this.target=b}fb.prototype.c=n;fb.prototype.b=o();function gb(a){gb[" "](a);return a}gb[" "]=o();function Q(a,b){a&&hb(this,a,b)}C(Q,fb);Q.prototype.target=l;Q.prototype.h=l;function hb(a,b,c){var d=a.type=b.type;fb.call(a,d);a.target=b.target||b.srcElement;a.a=c;if((c=b.relatedTarget)&&xa)try{gb(c.nodeName)}catch(e){}a.h=b;b.defaultPrevented&&a.b();delete a.c}Q.prototype.b=function(){Q.M.b.call(this);var a=this.h;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,eb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};function ib(){}var jb=0;ib.prototype.key=0;ib.prototype.r=n;ib.prototype.a=n;ib.prototype.handleEvent=function(a){return this.b?this.z.call(this.G||this.src,a):this.z.handleEvent.call(this.z,a)};function ab(a,b){var c,d=ba(b),d=(c="array"==d||"object"==d&&"number"==typeof b.length)?b:arguments;for(c=c?0:1;c<d.length&&!(a=a[d[c]],!s(a));c++);return a};var R={},S={},T={},U={};
function kb(a,b,c,d,e){if(b)if(ca(b))for(var f=0;f<b.length;f++)kb(a,b[f],c,d,e);else{var d=!!d,g=S;b in g||(g[b]={k:0,q:0});g=g[b];d in g||(g[d]={k:0,q:0},g.k++);var g=g[d],h=a[y]||(a[y]=++da),r;g.q++;if(g[h]){r=g[h];for(f=0;f<r.length;f++)if(g=r[f],g.z==c&&g.G==e){if(g.r)break;return}}else r=g[h]=[],g.k++;var t=lb,u=db?function(a){return t.call(u.src,u.key,a)}:function(a){a=t.call(u.src,u.key,a);if(!a)return a},f=u;f.src=a;var m=g=new ib;w(c)?m.b=k:c&&c.handleEvent&&w(c.handleEvent)?m.b=n:i(Error("Invalid listener argument"));
m.z=c;m.c=f;m.src=a;m.type=b;m.capture=!!d;m.G=e;m.a=n;m.key=++jb;m.r=n;c=g.key;f.key=c;r.push(g);R[c]=g;T[h]||(T[h]=[]);T[h].push(g);a.addEventListener?(a==q||!a.O)&&a.addEventListener(b,f,d):a.attachEvent(b in U?U[b]:U[b]="on"+b,f)}else i(Error("Invalid event type"))}function mb(a,b,c,d){if(!d.A&&d.L){for(var e=0,f=0;e<d.length;e++)d[e].r?d[e].c.src=l:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.L=n;0==f&&(delete S[a][b][c],S[a][b].k--,0==S[a][b].k&&(delete S[a][b],S[a].k--),0==S[a].k&&delete S[a])}}
function nb(a,b,c,d,e){var f=1,b=b[y]||(b[y]=++da);if(a[b]){a.q--;a=a[b];a.A?a.A++:a.A=1;try{for(var g=a.length,h=0;h<g;h++){var r=a[h];r&&!r.r&&(f&=ob(r,e)!==n)}}finally{a.A--,mb(c,d,b,a)}}return Boolean(f)}
function ob(a,b){if(a.a){var c=a.key;if(R[c]){var d=R[c];if(!d.r){var e=d.src,f=d.type,g=d.c,h=d.capture;e.removeEventListener?(e==q||!e.O)&&e.removeEventListener(f,g,h):e.detachEvent&&e.detachEvent(f in U?U[f]:U[f]="on"+f,g);e=e[y]||(e[y]=++da);if(T[e]){var g=T[e],r=Ja(g,d);0<=r&&K.splice.call(g,r,1);0==g.length&&delete T[e]}d.r=k;if(d=S[f][h][e])d.L=k,mb(f,h,e,d);delete R[c]}}}return a.handleEvent(b)}
function lb(a,b){if(!R[a])return k;var c=R[a],d=c.type,e=S;if(!(d in e))return k;var e=e[d],f,g;if(!db){f=b||aa("window.event");var h=k in e,r=n in e;if(h){if(0>f.keyCode||f.returnValue!=j)return k;a:{var t=n;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(u){t=k}if(t||f.returnValue==j)f.returnValue=k}}t=new Q;hb(t,f,this);f=k;try{if(h){for(var m=[],D=t.a;D;D=D.parentNode)m.push(D);g=e[k];g.q=g.k;for(var A=m.length-1;!t.c&&0<=A&&g.q;A--)t.a=m[A],f&=nb(g,m[A],d,k,t);if(r){g=e[n];g.q=g.k;for(A=0;!t.c&&
A<m.length&&g.q;A++)t.a=m[A],f&=nb(g,m[A],d,n,t)}}else f=ob(c,t)}finally{m&&(m.length=0)}return f}d=new Q(b,this);return f=ob(c,d)};var pb=q.window||q.self;function qb(a,b,c){this.name=a;this.type=c||"TEXT";this.unique=!!b}qb.prototype.toJSON=function(){return{name:this.name,type:this.type,unique:this.unique}};function rb(a,b,c,d){this.name=a;this.keyPath=b||"id";this.b=this.keyPath.split(".");this.B=!!c;this.a=d||[]}rb.prototype.toJSON=function(){for(var a=[],b=0;b<this.a.length;b++)a.push(this.a[b].toJSON());return{name:this.name,keyPath:this.keyPath,autoIncrement:this.B,indexes:a}};
function sb(a){var b=[],c=a.indexes||[];if(ca(c))for(var d=0;d<c.length;d++)b.push(new qb(c[d].name,c[d].type,c[d].unique));return new rb(a.name,a.keyPath,a.autoIncrement,b)}function tb(a,b){return b==a.keyPath?k:Ma(a.a,function(a){return a.name==b})}function ub(a,b,c){this.version=a||1;this.size=b||5242880;this.a=c||[]}ub.prototype.toJSON=function(){var a=this.a.map(function(a){return a.toJSON()});return{version:this.version,size:this.size,stores:a}};
function vb(a){for(var b=[],c=a.stores||[],d=0;d<c.length;d++)b.push(sb(c[d]));return new ub(a.version,a.size,b)}function P(a,b){return Na(a.a,function(a){return a.name==b})}function wb(a,b){return Ma(a.a,function(a){return a.name==b})};function xb(a){return yb(a||arguments.callee.caller,[])}
function yb(a,b){var c=[];if(0<=Ja(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(zb(a)+"(");for(var d=a.arguments,e=0;e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=zb(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(yb(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function zb(a){if(Ab[a])return Ab[a];a=String(a);if(!Ab[a]){var b=/function ([^\(]+)/.exec(a);Ab[a]=b?b[1]:"[Anonymous]"}return Ab[a]}var Ab={};function Bb(a,b,c,d,e){"number"==typeof e||Cb++;d||ga();this.c=b;delete this.b;delete this.a}Bb.prototype.b=l;Bb.prototype.a=l;var Cb=0;function V(){}V.prototype.a=l;V.prototype.c=l;V.prototype.b=l;function W(a,b){this.name=a;this.value=b}W.prototype.toString=function(){return this.name};var Db=new W("SEVERE",1E3),Eb=new W("WARNING",900),Fb=new W("CONFIG",700),Gb=new W("FINE",500),Hb=new W("FINER",400),Ib=new W("FINEST",300);function Jb(a){return a.c?a.c:a.a?Jb(a.a):l}
V.prototype.log=function(a,b,c){if(a.value>=Jb(this).value){a="log:"+this.h(a,b,c).c;q.console&&(q.console.timeStamp?q.console.timeStamp(a):q.console.markTimeline&&q.console.markTimeline(a));q.msWriteProfilerMark&&q.msWriteProfilerMark(a);for(a=this;a;)a=a.a}};
V.prototype.h=function(a,b,c){var d=new Bb(0,String(b));if(c){d.b=c;var e;var f=arguments.callee.caller;try{var g;var h=aa("window.location.href");if(v(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:h,stack:"Not available"};else{var r,t,u=n;try{r=c.lineNumber||c.U||"Not available"}catch(m){r="Not available",u=k}try{t=c.fileName||c.filename||c.sourceURL||h}catch(D){t="Not available",u=k}g=u||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:r,
fileName:t,stack:c.stack||"Not available"}:c}e="Message: "+ha(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+ha(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+ha(xb(f)+"-> ")}catch(A){e="Exception trying to expose exception! You win, we lose. "+A}d.a=e}return d};function X(a,b){a.log(Eb,b,j)}function Y(a,b){a.log(Hb,b,j)}function Kb(a,b){a.log(Ib,b,j)}var Lb={},Mb=l;
function Nb(a){Mb||(Mb=new V,Lb[""]=Mb,Mb.c=Fb);var b;if(!(b=Lb[a])){b=new V;var c=a.lastIndexOf("."),d=a.substr(c+1),c=Nb(a.substr(0,c));c.b||(c.b={});c.b[d]=b;b.a=c;Lb[a]=b}return b};var Ob=Nb("ydn");function cb(a){if(!v(a)||/^[\s\xa0]*$/.test(a))return{};try{return JSON.parse(a)}catch(b){X(Ob,"parse failed: "+b),i(Error(b))}}function bb(a){try{return JSON.stringify(a)}catch(b){return X(Ob,"stringify failed: "+b),""}};function Pb(a,b){var c=this;this.b=a;this.f=b;this.a=b[b.length-1];Y(c.g,"Trying to open "+this.b+" "+this.a.version);var d=Qb.open(this.b,this.a.version);d.onsuccess=function(a){Y(c.g,c.b+" "+c.a.version+" OK.");var b=a.target.result,d=b.version;if(w(b.setVersion)&&s(c.a.version)&&c.a.version>d){Y(c.g,"initializing database from "+b.version+" to "+c.a.version);var h=b.setVersion(c.a.version);h.V=function(){X(c.g,"migrating from "+b.version+" to "+c.a.version+" failed.");Rb(c,l)};h.onsuccess=function(){Sb(c,
d,b);Y(c.g,"Migrated to version "+b.version+".");Qb.open(c.b).onsuccess=function(){b=a.target.result;Y(c.g,"version "+b.version+" ready.");Rb(c,b)}}}else Y(c.g,"database version "+b.version+"ready to go"),Rb(c,b)};d.a=function(a){var b=a.target.result;Y(c.g,"upgrading version "+b.version);Sb(c,j,b);Qb.open(c.b).onsuccess=function(){b=a.target.result;Y(c.g,"Database: "+c.b+" upgraded.");Rb(c,b)}};d.onerror=function(){c.g.log(Db,"opening database "+a+" failed.",j);c.db=l};d.onversionchange=function(){c.g.log(Gb,
"Version change request, so closing the database",j);c.db&&c.db.close()}}var Qb=q.indexedDB||q.mozIndexedDB||q.webkitIndexedDB||q.moz_indexedDB||q.msIndexedDB,Tb=q.IDBKeyRange||q.webkitIDBKeyRange;p=Pb.prototype;p.g=Nb("ydn.db.IndexedDb");function Rb(a,b){Kb(a.g,"Setting DB: "+b.name+" ver: "+b.version);a.l=b;a.h=k;a.c&&Ub(a)}
function Sb(a,b,c){for(var d=Na(a.f,function(a){return a.version==b}),e,f=0;e=a.a.a[f];f++){Kb(a.g,"Creating Object Store for "+e.name+" keyPath: "+e.keyPath);var g;if(!(g=!d))g=P(d,e.name)===l;if(g)try{for(var h=c.createObjectStore(e.name,{keyPath:e.keyPath,B:e.B}),f=0;f<e.a.length;f++){var r=e.a[f];h.createIndex(r.name,r.name,{unique:r.unique})}Kb(a.g,"Created store: "+h.name+" keyPath: "+h.keyPath)}catch(t){X(a.g,t.message)}}}
function Ub(a){if(a.l&&a.c){var b=a.c.shift();b&&Z(a,b.Q,b.T,b.mode,b.P)}}function Z(a,b,c,d,e){e=e||new L;if(a.h){a.h=n;var f=a.l.transaction(c,d);kb(f,["complete","abort","error"],function(){function b(){a.h=k;Ub(a)}s(f.n)?e.d(f.result):e.e(j);w(b)||(b&&"function"==typeof b.handleEvent?b=z(b.handleEvent,b):i(Error("Invalid listener argument")));pb.setTimeout(b,0)});b(f)}else a.c||(a.c=[]),a.c.push({Q:b,T:c,mode:d,P:e});return e}
p.put=function(a,b){wb(this.a,a)||i(Error(a+" not exist in "+this.b));return Z(this,function(c){var d=c.objectStore(a),e;if(ca(b))for(var f=0;f<b.length;f++)e=d.put(b[f]);else e=d.put(b);e.onsuccess=function(){c.n=k;c.result=k};e.onerror=o()},[a],"readwrite")};
p.get=function(a,b){if(!s(b))return wb(this.a,a)||i(Error("Store: "+a+" not exist.")),Z(this,function(b){var c=b.objectStore(a),f=Tb.lowerBound(0),c=c.openCursor(f);c.onsuccess=function(a){b.n=k;s(b.result)||(b.result=[]);a=a.target.result;!!a!=n&&(s(a.value)&&b.result.push(a.value),a["continue"]())};c.onerror=o()},[a],"readonly");wb(this.a,a)||i(Error("Store: "+a+" not exist."));var c=this;return Z(this,function(d){var e=d.objectStore(a).get(b);e.onsuccess=function(a){d.n=k;d.result=a.target.result};
e.onerror=function(){X(c.g,"Error retriving "+b+" in "+a)}},[a],"readonly")};
p.p=function(a){var b=a.value,c=a.c,d=a.a||"default_text_store";c||(c=this.a[a.a].keyPath);return Z(this,function(e){var f=e.objectStore(d).index(c),g;g="";if(a.b=="st"){g=b.substring(0,b.length-1)+String.fromCharCode(b.charCodeAt(b.length-1)+1);g=Tb.bound(b,g,n,k)}else g=Tb.only(b);f=f.openCursor(g);f.onsuccess=function(a){e.n=k;if(a=a.target.result){if(!e.result)e.result=[];e.result.push(a.value);a["continue"]()}};f.onerror=o()},[d],"readwrite")};
p.remove=function(a,b){if(s(a)){var c;s(b)?(wb(this.a,a)||i(Error(a+" not exist in "+this.b)),c=Z(this,function(c){var d=c.objectStore(a)["delete"](b);d.onsuccess=function(){c.n=k;c.result=k};d.onerror=o()},[a],"readwrite")):(wb(this.a,a)||i(Error(a+" not exist in "+this.b)),c=Z(this,function(b){var c=b.deleteObjectStore(a);c.onsuccess=function(){b.n=k;b.result=k};c.onerror=o()},[a],"readwrite"));return c}if(w(Qb.deleteDatabase)){var d=new L;c=Qb.deleteDatabase(this.b);c.onsuccess=function(a){d.j(a)};
c.onerror=function(a){d.u(a)};return d}return Vb(this)};function Vb(a){for(var b=[],c=0;c<a.a.a.length;c++)b.push(a.clear(a.a.a[c].name));return Ya(new O(b))}p.clear=function(a){return!s(a)?Vb(this):Z(this,function(b){var c=b.objectStore(a).clear();c.onsuccess=function(){b.n=k;b.result=k};c.onerror=o()},[a],"readwrite")};p.count=function(a){return Z(this,function(b){var c=b.objectStore(a).count();c.onsuccess=function(a){b.n=k;b.result=a.target.result};c.onerror=o()},[a],"readonly")};function Wb(a,b){this.b=b[b.length-1];this.a={};for(var c in this.b)this.a[c]={}}p=Wb.prototype;p.put=function(a,b){this.a[a][b[this.b[a].keyPath]]=b;return N(k)};p.get=function(a,b){var c=this.b[a].keyPath,d;for(d in this.a[a]){var e=this.a[a][d];if(e[c]===b)return N(e)}return Xa(j)};p.clear=function(a){if(s(a))this.a[a]={};else for(var b in this.a)this.a[b]={};return N(k)};p.count=function(a){var a=a||"default_text_store",b=new L,c=0,d;for(d in this.a[a])c++;b.d(c);return b};p.p=function(){return Xa(k)};
p.remove=function(a,b){return s(a)&&s(b)?(delete this.a[a][b],N(k)):this.clear()};function Xb(a,b){this.b=a;this.f=b;this.a=b[b.length-1];this.db=q.openDatabase(this.b,"",this.b,this.a.size);if(this.db.version!=this.a.version){for(var c=this,d=function(){Kb(c.i,"Creating tables OK.")},e=function(){X(c.i,"Error creating tables")},f=[],g=0;g<this.a.a.length;g++)f.push(Yb(this.a.a[g]));this.db.transaction(function(a){Kb(c.i,"Creating tables "+f.join("\n"));for(var b=0;b<f.length;b++)a.executeSql(f[b],[],b==f.length-1?d:j,e)})}}p=Xb.prototype;p.i=Nb("ydn.db.WebSql");
function Yb(a){var b="CREATE TABLE IF NOT EXISTS "+F(a.name)+" ("+F(a.keyPath)+" TEXT UNIQUE PRIMARY KEY";Na(a.a,function(a){return"_default_"==a.name})||a.a.push(new qb("_default_",j,j));for(var c=0;c<a.a.length;c++)var d=a.a[c],b=b+(", "+d.name+(d.unique?" UNIQUE ":" ")+d.type);return b+");"}
p.put=function(a,b){function c(a,b){X(h.i,"put error: "+b);e.e(j)}function d(){e.d(k)}var e=new L,f=P(this.a,a);if(!f)return X(this.i,"Table "+a+" not found."),e.e(j),e;var g=ca(b)?b:[b],h=this;h.db.transaction(function(a){for(var b,e,h,D=0;D<g.length;D++){var A=D==g.length-1;b=f;var ia=g[D],Va=[F(b.keyPath)];h=[ab(ia,b.b)];e=["?"];for(var E=0;E<b.a.length;E++)if("_default_"!=b.a[E].name){var x=ia[b.a[E].name];s(x)&&("INTEGER"==b.a[E].type?"number"==typeof x||(x=parseInt(x,10)):"REAL"==b.a[E].type?
"number"==typeof x||(x=parseFloat(x)):v(x)||(x=bb(x)),h.push(x),e.push("?"),Va.push(F(b.a[E].name)))}E={};x=j;for(x in ia)ia.hasOwnProperty(x)&&!tb(b,x)&&(E[x]=ia[x]);h.push(bb(E));e.push("?");Va.push("_default_");b=Va;e="INSERT OR REPLACE INTO "+F(f.name)+" ("+b.join(", ")+") VALUES ("+e.join(", ")+");";a.executeSql(e,h,A?d:j,A?c:j)}});return e};
function Zb(a,b){for(var c=cb(b._default_),d=c,e=b[a.keyPath],f=0;f<a.b.length;f++){var g=a.b[f];if(f==a.b.length-1){d[g]=e;break}s(d[g])||(d[g]={});d=d[g]}for(d=0;d<a.a.length;d++)e=a.a[d],"_default_"!=e.name&&(f=b[e.name],s(f)&&("INTEGER"==e.type?f=parseInt(f,10):"REAL"==e.type&&(f=parseFloat(f)),c[e.name]=f));return c}
p.get=function(a,b){function c(a,b){X(g.i,"get error: "+b);e.e(j)}function d(a,c){if(s(b))0<c.rows.length?(h=c.rows.item(0),e.d(Zb(f,h))):e.d(j);else{for(var d=[],g=0;g<c.rows.length;g++){var h=c.rows.item(g);d.push(Zb(f,h))}e.d(d)}}var e=new L,f=P(this.a,a);f||(X(this.i,"Table "+a+" not found."),e.e(j));var g=this,h=s(b)?"SELECT * FROM "+F(f.name)+" WHERE "+F(f.keyPath)+" = "+F(b)+";":"SELECT * FROM "+F(f.name);this.db.transaction(function(a){a.executeSql(h,[],d,c)});return e};
p.p=function(a){function b(a,b){X(e.i,"Sqlite error: "+b);d.e(j)}function c(a,b){for(var c=[],e=0;e<b.rows.length;e++){var g=b.rows.item(e);c.push(Zb(f,g))}d.d(c)}var d=new L,e=this,f=P(this.a,a.a),g=a.c||f.keyPath,h="SELECT * FROM "+F(f.name)+" WHERE ",h="st"==a.b?h+("("+g+" LIKE ?)"):h+("("+F(g)+" = ?)");this.db.transaction(function(d){d.executeSql(h,[a.value+"%"],c,b)});return d};
function $b(a,b){function c(b,c){X(a.i,"Sqlite error: "+c);e.e(j)}function d(){e.d(k)}var e=new L,f="";if(s(b))P(a.a,b)||i(Error("Table "+b+" not found.")),f="DELETE FROM  "+b;else for(var g=0;g<a.a.a.length;g++)f="DELETE FROM  "+a.a.a[g].name+"; ";a.db.transaction(function(a){a.executeSql(f,[],d,c)});return e}
p.count=function(a){function b(a,b){X(e.i,"count error: "+b);d.e(j)}function c(a,b){var c=b.rows.item(0);d.d(c["COUNT(*)"])}var d=new L,e=this,f="SELECT COUNT(*) FROM "+(a||"default_text_store");this.db.transaction(function(a){a.executeSql(f,[],c,b)});return d};p.clear=function(a){if(a)return $b(this,a);var a=[],b;for(b in this.a)a.push($b(this,b));return Ya(new O(a))};
p.remove=function(a,b){var c;if(s(a))if(s(b)){var d=new L,e=P(this.a,a);if(e){var f=this,g=function(){d.d(k)},h=function(a,b){X(f.i,"put error: "+b);d.e(j)};f.db.transaction(function(a){var c="DELETE FROM "+F(e.name)+" WHERE "+F(e.keyPath)+" = "+F(b);a.executeSql(c,[],g,h)})}else X(this.i,"Table "+a+" not found."),d.e(j);c=d}else c=ac(this,a);else c=ac(this);return c};
function ac(a,b){function c(b,c){X(a.i,"Delete TABLE: "+c);e.e(j)}function d(){e.d(k);X(a.i,"Deleted database: "+a.b)}var e=new L,f="";if(s(b)){var g=P(a.a,b);g||i(Error("Table "+b+" not found."));f=f+"DROP TABLE "+F(g.name)+";"}else for(g=0;g<a.a.a.length;g++)f=f+"DROP TABLE "+F(a.a.a[g].name)+";";a.db.transaction(function(a){a.executeSql(f,[],d,c)});return e};/*
 Copyright 2012 YDN Authors. All Rights Reserved.
*/
function $(a,b){this.b=new L;s(a)&&this.h(a);s(b)&&this.l(b)}$.prototype.w=function(){this.c()||i(Error("Database not initialized."));var a=this.f.map(function(a){return a.toJSON()});return{o:this.o,f:a}};B("ydn.db.Storage.prototype.getConfig",$.prototype.w);$.prototype.h=function(a){this.a&&i(Error("DB already initialized"));this.o=a.replace(/[@|\.|\s]/g,"");bc(this);return this.o};B("ydn.db.Storage.prototype.setDbName",$.prototype.h);
$.prototype.v=function(a){var b=!s(this.f);a instanceof ub||(a=vb(a));this.f=this.f||[];this.f.push(a);b?bc(this):i(Error("Schema migration not supported yet."))};B("ydn.db.Storage.prototype.addSchema",$.prototype.v);$.prototype.l=function(a){var b=a;if(!(a[0]instanceof ub))for(var b=[],c=0;c<a.length;c++)b.push(vb(a[c]));this.f=b||[];bc(this)};B("ydn.db.Storage.prototype.setSchemas",$.prototype.l);
function bc(a){if(s(a.o)&&s(a.f)){var b=a.f[a.f.length-1];!/^[\s\xa0]*$/.test("default_text_store")&&!wb(b,"default_text_store")&&b.a.push(new rb("default_text_store"));Qb?a.a=new Pb(a.o,a.f):w(q.openDatabase)?a.a=new Xb(a.o,a.f):window.localStorage?a.a=new Za(a.o,a.f):a.a=new Wb(0,a.f);a.b.m&&(a.b=new L);a.b.d(a.a)}}$.prototype.c=function(){return!!this.a};B("ydn.db.Storage.prototype.isReady",$.prototype.c);$.prototype.setItem=function(a,b){return this.put("default_text_store",{id:a,value:b})};
B("ydn.db.Storage.prototype.setItem",$.prototype.setItem);$.prototype.put=function(a,b){if(this.a)return this.a.put(a,b);var c=new L;this.b.j(function(d){M(d.put(a,b),c)});return c};B("ydn.db.Storage.prototype.put",$.prototype.put);$.prototype.getItem=function(a){var a=this.get("default_text_store",a),b=new L;a.j(function(a){s(a)?b.d(a.value):b.d(j)});a.u(function(a){b.e(a)});return b};B("ydn.db.Storage.prototype.getItem",$.prototype.getItem);
$.prototype.get=function(a,b){if(this.a)return this.a.get(a,b);var c=new L;this.b.j(function(d){M(d.get(a,b),c)});return c};B("ydn.db.Storage.prototype.get",$.prototype.get);$.prototype.clear=function(a){if(this.a)return this.a.clear(a);var b=new L;this.b.j(function(c){M(c.clear(a),b)});return b};B("ydn.db.Storage.prototype.clear",$.prototype.clear);$.prototype.remove=function(a,b){if(this.a)return this.a.remove(a,b);var c=new L;this.b.j(function(d){M(d.remove(a,b),c)});return c};
B("ydn.db.Storage.prototype.remove",$.prototype.remove);$.prototype.count=function(a){if(this.a)return this.a.count(a);var b=new L;this.b.j(function(c){M(c.count(a),b)});return b};B("ydn.db.Storage.prototype.count",$.prototype.count);$.prototype.p=function(a){if(this.a)return this.a.p(a);var b=new L;this.b.j(function(c){M(c.p(a),b)});return b};B("ydn.db.Storage.prototype.fetch",$.prototype.p);B("ydn.db.Storage",$);L.prototype.success=L.prototype.j;L.prototype.error=L.prototype.u;})();
