(function(){var i=void 0,j=!0,l=null,m=!1;function n(){return function(){}}var o,p=this;function aa(a){for(var a=a.split("."),b=p,c;c=a.shift();)if(b[c]!=l)b=b[c];else return l;return b}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function r(a){return a!==i}function ca(a){return"array"==ba(a)}function u(a){return"string"==typeof a}function w(a){return"function"==ba(a)}var y="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function z(a,b,c){z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return z.apply(l,arguments)}var ga=Date.now||function(){return+new Date};
function A(a,b){var c=a.split("."),d=p;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&r(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function D(a,b){function c(){}c.prototype=b.prototype;a.N=b.prototype;a.prototype=new c};function ia(a){if(!ja.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ka,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(la,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ma,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(na,"&quot;"));return a}var ka=/&/g,la=/</g,ma=/>/g,na=/\"/g,ja=/[&<>\"]/,oa={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},pa={"'":"\\'"};
function E(a){a=String(a);if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=b,g=c+1,h;if(!(h=oa[d])){if(!(31<e&&127>e))if(d in pa)d=pa[d];else if(d in oa)d=pa[d]=oa[d];else{e=d;h=d.charCodeAt(0);if(31<h&&127>h)e=d;else{if(256>h){if(e="\\x",16>h||256<h)e+="0"}else e="\\u",4096>h&&(e+="0");e+=h.toString(16).toUpperCase()}d=pa[d]=e}h=d}f[g]=h}b.push('"');return b.join("")};var F,qa,ra,sa;function ta(){return p.navigator?p.navigator.userAgent:l}sa=ra=qa=F=m;var ua;if(ua=ta()){var va=p.navigator;F=0==ua.indexOf("Opera");qa=!F&&-1!=ua.indexOf("MSIE");ra=!F&&-1!=ua.indexOf("WebKit");sa=!F&&!ra&&"Gecko"==va.product}var wa=F,G=qa,xa=sa,ya=ra,za;
a:{var Aa="",Ba;if(wa&&p.opera)var Ca=p.opera.version,Aa="function"==typeof Ca?Ca():Ca;else if(xa?Ba=/rv\:([^\);]+)(\)|;)/:G?Ba=/MSIE\s+([^\);]+)(\)|;)/:ya&&(Ba=/WebKit\/(\S+)/),Ba)var Da=Ba.exec(ta()),Aa=Da?Da[1]:"";if(G){var Ea,Fa=p.document;Ea=Fa?Fa.documentMode:i;if(Ea>parseFloat(Aa)){za=String(Ea);break a}}za=Aa}var Ga={};
function H(a){var b;if(!(b=Ga[a])){b=0;for(var c=String(za).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",q=/(\d*)(\D*)/g,s=/(\d*)(\D*)/g;do{var t=q.exec(g)||["","",""],k=s.exec(h)||["","",""];if(0==t[0].length&&0==k[0].length)break;b=((0==t[1].length?0:parseInt(t[1],10))<(0==k[1].length?0:parseInt(k[1],10))?-1:(0==t[1].length?0:parseInt(t[1],10))>(0==k[1].length?
0:parseInt(k[1],10))?1:0)||((0==t[2].length)<(0==k[2].length)?-1:(0==t[2].length)>(0==k[2].length)?1:0)||(t[2]<k[2]?-1:t[2]>k[2]?1:0)}while(0==b)}b=Ga[a]=0<=b}return b}var Ha={};function Ia(){return Ha[9]||(Ha[9]=G&&!!document.documentMode&&9<=document.documentMode)};function I(a){Error.captureStackTrace?Error.captureStackTrace(this,I):this.stack=Error().stack||"";a&&(this.message=String(a))}D(I,Error);I.prototype.name="CustomError";var J=Array.prototype,Ja=J.indexOf?function(a,b,c){return J.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(u(a))return!u(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ka=J.forEach?function(a,b,c){J.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},La=J.some?function(a,b,c){return J.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,
f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return j;return m};function Ma(a,b){var c;a:{c=a.length;for(var d=u(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(i,d[e],e,a)){c=e;break a}c=-1}return 0>c?l:u(a)?a.charAt(c):a[c]};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function K(a,b){this.c=[];this.v=a;this.w=b||l}o=K.prototype;o.n=m;o.t=m;o.u=0;o.F=m;o.O=m;o.D=0;o.cancel=function(a){if(this.n)this.b instanceof K&&this.b.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.D--,0>=b.D&&b.cancel())}this.v?this.v.call(this.w,this):this.F=j;this.n||this.e(new Na)}};o.G=function(a,b){Oa(this,a,b);this.u--;0==this.u&&this.n&&Pa(this)};function Oa(a,b,c){a.n=j;a.b=c;a.t=!b;Pa(a)}function Qa(a){if(a.n){if(!a.F)throw new Sa;a.F=m}}
o.d=function(a){Qa(this);Oa(this,j,a)};o.e=function(a){Qa(this);Oa(this,m,a)};o.k=function(a,b){return Ta(this,a,l,b)};o.B=function(a,b){return Ta(this,l,a,b)};function Ta(a,b,c,d){a.c.push([b,c,d]);a.n&&Pa(a);return a}function L(a,b){Ta(a,b.d,b.e,b)}function Ua(a){return La(a.c,function(a){return w(a[1])})}
function Pa(a){a.m&&(a.n&&Ua(a))&&(p.clearTimeout(a.m),delete a.m);a.a&&(a.a.D--,delete a.a);for(var b=a.b,c=m,d=m;a.c.length&&0==a.u;){var e=a.c.shift(),f=e[0],g=e[1],e=e[2];if(f=a.t?g:f)try{var h=f.call(e||a.w,b);r(h)&&(a.t=a.t&&(h==b||h instanceof Error),a.b=b=h);b instanceof K&&(d=j,a.u++)}catch(q){b=q,a.t=j,Ua(a)||(c=j)}}a.b=b;d&&a.u&&(Ta(b,z(a.G,a,j),z(a.G,a,m)),b.O=j);c&&(a.m=p.setTimeout(function(){throw new Va(b);},0))}function M(a){var b=new K;b.d(a);return b}
function Wa(a){var b=new K;b.e(a);return b}function Sa(){I.call(this)}D(Sa,I);Sa.prototype.message="Already called";function Na(){I.call(this)}D(Na,I);Na.prototype.message="Deferred was cancelled";function Va(a){I.call(this);this.message="Unhandled Error in Deferred: "+(a.message||"[No message]")}D(Va,I);function N(a,b,c,d,e,f){K.call(this,e,f);this.K=a;this.g=[];this.I=!!b;this.T=!!c;this.S=!!d;for(b=0;b<a.length;b++)Ta(a[b],z(this.J,this,b,j),z(this.J,this,b,m));0==a.length&&!this.I&&this.d(this.g)}D(N,K);N.prototype.L=0;N.prototype.J=function(a,b,c){this.L++;this.g[a]=[b,c];this.n||(this.I&&b?this.d([a,c]):this.T&&!b?this.e(c):this.L==this.K.length&&this.d(this.g));this.S&&!b&&(c=l);return c};N.prototype.e=function(a){N.N.e.call(this,a);Ka(this.K,function(a){a.cancel()})};function Xa(a){var b=new K;a.k(function(a){a.every(function(a){return!!a})?b.d(j):b.e(i)});a.B(function(a){b.e(a)});return b};function Ya(a,b){this.a=a;this.f=b;this.b=b[b.length-1]}o=Ya.prototype;o.put=function(a,b){var c=O(this.b,a),d,e;d=typeof b;if("object"==d&&b!=l||"function"==d)d=Za(b,c.b),d="_database_"+this.a+"-"+a+"-"+d,e=$a(b),window.localStorage.setItem(d,e);else if(ca(b))for(var f=0;f<b.length;f++)d=Za(b[f],c.b),d="_database_"+this.a+"-"+a+"-"+d,e=$a(b),window.localStorage.setItem(d,e);else throw Error("Not object: "+b);return M(j)};
o.get=function(a,b){O(this.b,a);var c=window.localStorage.getItem("_database_"+this.a+"-"+a+"-"+b);return M(ab(c))};o.clear=function(a){r(a)?a=[a]:(a=this.b,a.a||(a.a=a.j.map(function(a){return a.name})),a=a.a);for(var b in window.localStorage)for(var c,d=0;c=a[d];d++)0==b.lastIndexOf("_database_"+this.a+"-"+c,0)&&delete window.localStorage[b];return M(j)};o.p=function(){return this.clear()};
o.count=function(){var a=new K,b=0,c;for(c in window.localStorage)0==c.lastIndexOf("_database_"+this.a,0)&&b++;a.d(b);return a};o.q=function(){return Wa(j)};!G||Ia();var bb=!G||Ia(),cb=G&&!H("8");!ya||H("528");xa&&H("1.9b")||G&&H("8")||wa&&H("9.5")||ya&&H("528");xa&&!H("8")||G&&H("9");function db(a,b){this.type=a;this.a=this.target=b}db.prototype.c=m;db.prototype.b=n();function eb(a){eb[" "](a);return a}eb[" "]=n();function P(a,b){a&&fb(this,a,b)}D(P,db);P.prototype.target=l;P.prototype.g=l;function fb(a,b,c){var d=a.type=b.type;db.call(a,d);a.target=b.target||b.srcElement;a.a=c;if((c=b.relatedTarget)&&xa)try{eb(c.nodeName)}catch(e){}a.g=b;b.defaultPrevented&&a.b();delete a.c}P.prototype.b=function(){P.N.b.call(this);var a=this.g;if(a.preventDefault)a.preventDefault();else if(a.returnValue=m,cb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};function gb(){}var hb=0;gb.prototype.key=0;gb.prototype.s=m;gb.prototype.a=m;gb.prototype.handleEvent=function(a){return this.b?this.z.call(this.H||this.src,a):this.z.handleEvent.call(this.z,a)};function Za(a,b){var c,d=ba(b),d=(c="array"==d||"object"==d&&"number"==typeof b.length)?b:arguments;for(c=c?0:1;c<d.length&&!(a=a[d[c]],!r(a));c++);return a};var Q={},R={},S={},T={};
function ib(a,b,c,d,e){if(b)if(ca(b))for(var f=0;f<b.length;f++)ib(a,b[f],c,d,e);else{var d=!!d,g=R;b in g||(g[b]={l:0,r:0});g=g[b];d in g||(g[d]={l:0,r:0},g.l++);var g=g[d],h=a[y]||(a[y]=++da),q;g.r++;if(g[h]){q=g[h];for(f=0;f<q.length;f++)if(g=q[f],g.z==c&&g.H==e){if(g.s)break;return}}else q=g[h]=[],g.l++;var s=jb,t=bb?function(a){return s.call(t.src,t.key,a)}:function(a){a=s.call(t.src,t.key,a);if(!a)return a},f=t;f.src=a;var k=g=new gb;if(w(c))k.b=j;else if(c&&c.handleEvent&&w(c.handleEvent))k.b=
m;else throw Error("Invalid listener argument");k.z=c;k.c=f;k.src=a;k.type=b;k.capture=!!d;k.H=e;k.a=m;k.key=++hb;k.s=m;c=g.key;f.key=c;q.push(g);Q[c]=g;S[h]||(S[h]=[]);S[h].push(g);a.addEventListener?(a==p||!a.P)&&a.addEventListener(b,f,d):a.attachEvent(b in T?T[b]:T[b]="on"+b,f)}else throw Error("Invalid event type");}
function kb(a,b,c,d){if(!d.A&&d.M){for(var e=0,f=0;e<d.length;e++)d[e].s?d[e].c.src=l:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.M=m;0==f&&(delete R[a][b][c],R[a][b].l--,0==R[a][b].l&&(delete R[a][b],R[a].l--),0==R[a].l&&delete R[a])}}function lb(a,b,c,d,e){var f=1,b=b[y]||(b[y]=++da);if(a[b]){a.r--;a=a[b];a.A?a.A++:a.A=1;try{for(var g=a.length,h=0;h<g;h++){var q=a[h];q&&!q.s&&(f&=mb(q,e)!==m)}}finally{a.A--,kb(c,d,b,a)}}return Boolean(f)}
function mb(a,b){if(a.a){var c=a.key;if(Q[c]){var d=Q[c];if(!d.s){var e=d.src,f=d.type,g=d.c,h=d.capture;e.removeEventListener?(e==p||!e.P)&&e.removeEventListener(f,g,h):e.detachEvent&&e.detachEvent(f in T?T[f]:T[f]="on"+f,g);e=e[y]||(e[y]=++da);if(S[e]){var g=S[e],q=Ja(g,d);0<=q&&J.splice.call(g,q,1);0==g.length&&delete S[e]}d.s=j;if(d=R[f][h][e])d.M=j,kb(f,h,e,d);delete Q[c]}}}return a.handleEvent(b)}
function jb(a,b){if(!Q[a])return j;var c=Q[a],d=c.type,e=R;if(!(d in e))return j;var e=e[d],f,g;if(!bb){f=b||aa("window.event");var h=j in e,q=m in e;if(h){if(0>f.keyCode||f.returnValue!=i)return j;a:{var s=m;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(t){s=j}if(s||f.returnValue==i)f.returnValue=j}}s=new P;fb(s,f,this);f=j;try{if(h){for(var k=[],B=s.a;B;B=B.parentNode)k.push(B);g=e[j];g.r=g.l;for(var x=k.length-1;!s.c&&0<=x&&g.r;x--)s.a=k[x],f&=lb(g,k[x],d,j,s);if(q){g=e[m];g.r=g.l;for(x=0;!s.c&&
x<k.length&&g.r;x++)s.a=k[x],f&=lb(g,k[x],d,m,s)}}else f=mb(c,s)}finally{k&&(k.length=0)}return f}d=new P(b,this);return f=mb(c,d)};var nb=p.window||p.self;function ob(a,b,c){this.name=a;this.type=c||"TEXT";this.unique=!!b}ob.prototype.toJSON=function(){return{name:this.name,type:this.type,unique:this.unique}};function pb(a,b,c,d){this.name=a;this.keyPath=b||"id";this.b=this.keyPath.split(".");this.C=!!c;this.a=d||[]}pb.prototype.toJSON=function(){for(var a=[],b=0;b<this.a.length;b++)a.push(this.a[b].toJSON());return{name:this.name,keyPath:this.keyPath,autoIncrement:this.C,indexes:a}};
function qb(a){var b=[],c=ab(a.indexes);if(ca(c))for(var d=0;d<c.length;d++)b.push(new ob(c[d].name,c[d].type,c[d].unique));return new pb(a.name,a.keyPath,a.autoIncrement,b)}function rb(a,b){return b==a.keyPath?j:a.a.some(function(a){return a.name==b})}function sb(a,b,c){this.version=a;this.size=b||5242880;this.j=c||[]}sb.prototype.toJSON=function(){return{version:this.version,size:this.size,stores:$a(this.j)}};
function tb(a){for(var b=[],c=ab(a.stores),d=0;d<c.length;d++)b.push(qb(c[d]));return new sb(a.version,a.size,b)}A("ydn.db.DatabaseSchema.fromJSON",tb);function O(a,b){return Ma(a.j,function(a){return a.name==b})}function ub(a,b){return a.j.some(function(a){return a.name==b})};function vb(a){return wb(a||arguments.callee.caller,[])}
function wb(a,b){var c=[];if(0<=Ja(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(xb(a)+"(");for(var d=a.arguments,e=0;e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=xb(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(wb(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function xb(a){if(yb[a])return yb[a];a=String(a);if(!yb[a]){var b=/function ([^\(]+)/.exec(a);yb[a]=b?b[1]:"[Anonymous]"}return yb[a]}var yb={};function zb(a,b,c,d,e){"number"==typeof e||Ab++;d||ga();this.c=b;delete this.b;delete this.a}zb.prototype.b=l;zb.prototype.a=l;var Ab=0;function U(){}U.prototype.a=l;U.prototype.c=l;U.prototype.b=l;function V(a,b){this.name=a;this.value=b}V.prototype.toString=function(){return this.name};var Bb=new V("SEVERE",1E3),Cb=new V("WARNING",900),Db=new V("CONFIG",700),Eb=new V("FINE",500),Fb=new V("FINER",400),Gb=new V("FINEST",300);function Hb(a){return a.c?a.c:a.a?Hb(a.a):l}
U.prototype.log=function(a,b,c){if(a.value>=Hb(this).value){a="log:"+this.g(a,b,c).c;p.console&&(p.console.timeStamp?p.console.timeStamp(a):p.console.markTimeline&&p.console.markTimeline(a));p.msWriteProfilerMark&&p.msWriteProfilerMark(a);for(a=this;a;)a=a.a}};
U.prototype.g=function(a,b,c){var d=new zb(0,String(b));if(c){d.b=c;var e;var f=arguments.callee.caller;try{var g;var h=aa("window.location.href");if(u(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:h,stack:"Not available"};else{var q,s,t=m;try{q=c.lineNumber||c.V||"Not available"}catch(k){q="Not available",t=j}try{s=c.fileName||c.filename||c.sourceURL||h}catch(B){s="Not available",t=j}g=t||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:q,
fileName:s,stack:c.stack||"Not available"}:c}e="Message: "+ia(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+ia(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+ia(vb(f)+"-> ")}catch(x){e="Exception trying to expose exception! You win, we lose. "+x}d.a=e}return d};function W(a,b){a.log(Cb,b,i)}function X(a,b){a.log(Fb,b,i)}function Ib(a,b){a.log(Gb,b,i)}var Jb={},Kb=l;
function Lb(a){Kb||(Kb=new U,Jb[""]=Kb,Kb.c=Db);var b;if(!(b=Jb[a])){b=new U;var c=a.lastIndexOf("."),d=a.substr(c+1),c=Lb(a.substr(0,c));c.b||(c.b={});c.b[d]=b;b.a=c;Jb[a]=b}return b};var Mb=Lb("ydn");function ab(a){if(!u(a)||/^[\s\xa0]*$/.test(a))return{};try{return JSON.parse(a)}catch(b){throw W(Mb,"parse failed: "+b),Error(b);}}function $a(a){try{return JSON.stringify(a)}catch(b){return W(Mb,"stringify failed: "+b),""}};function Nb(a,b){var c=this;this.b=a;this.f=b;this.a=b[b.length-1];X(c.h,"Trying to open "+this.b+" "+this.a.version);var d=Y.open(this.b,this.a.version);d.onsuccess=function(a){X(c.h,c.b+" "+c.a.version+" OK.");var b=a.target.result,d=b.version;if(w(b.setVersion)&&r(c.a.version)&&c.a.version>d){X(c.h,"initializing database from "+b.version+" to "+c.a.version);var h=b.setVersion(c.a.version);h.W=function(){W(c.h,"migrating from "+b.version+" to "+c.a.version+" failed.");Ob(c,l)};h.onsuccess=function(){Pb(c,
d,b);X(c.h,"Migrated to version "+b.version+".");Y.open(c.b).onsuccess=function(){b=a.target.result;X(c.h,"version "+b.version+" ready.");Ob(c,b)}}}else X(c.h,"database version "+b.version+"ready to go"),Ob(c,b)};d.a=function(a){var b=a.target.result;X(c.h,"upgrading version "+b.version);Pb(c,i,b);Y.open(c.b).onsuccess=function(){b=a.target.result;X(c.h,"Database: "+c.b+" upgraded.");Ob(c,b)}};d.onerror=function(){c.h.log(Bb,"opening database "+a+" failed.",i);c.db=l};d.onversionchange=function(){c.h.log(Eb,
"Version change request, so closing the database",i);c.db&&c.db.close()}}var Y=p.indexedDB||p.mozIndexedDB||p.webkitIndexedDB||p.moz_indexedDB||p.msIndexedDB,Qb=p.IDBKeyRange||p.webkitIDBKeyRange;o=Nb.prototype;o.h=Lb("ydn.db.IndexedDb");function Ob(a,b){Ib(a.h,"Setting DB: "+b.name+" ver: "+b.version);a.m=b;a.g=j;a.c&&Rb(a)}
function Pb(a,b,c){for(var d=Ma(a.f,function(a){return a.version==b}),e,f=0;e=a.a.j[f];f++){Ib(a.h,"Creating Object Store for "+e.name+" keyPath: "+e.keyPath);var g;if(!(g=!d))g=O(d,e.name)===l;if(g)try{for(var h=c.createObjectStore(e.name,{keyPath:e.keyPath,C:e.C}),f=0;f<e.a.length;f++){var q=e.a[f];h.createIndex(q.name,q.name,{unique:q.unique})}Ib(a.h,"Created store: "+h.name+" keyPath: "+h.keyPath)}catch(s){W(a.h,s.message)}}}
function Rb(a){if(a.m){var b=a.c.shift();b&&Z(a,b.R,b.U,b.mode,b.Q)}}function Z(a,b,c,d,e){e=e||new K;if(a.g){a.g=m;var f=a.m.transaction(c,d);ib(f,["complete","abort","error"],function(){function b(){a.g=j;Rb(a)}r(f.result)?e.d(f.result):e.e(i);if(!w(b))if(b&&"function"==typeof b.handleEvent)b=z(b.handleEvent,b);else throw Error("Invalid listener argument");nb.setTimeout(b,0)});b(f)}else a.c||(a.c=[]),a.c.push({R:b,U:c,mode:d,Q:e});return e}
o.put=function(a,b){if(!ub(this.a,a))throw Error(a+" not exist in "+this.b);return Z(this,function(c){var d=c.objectStore(a),e;if(ca(b))for(var f=0;f<b.length;f++)e=d.put(b[f]);else e=d.put(b);e.onsuccess=function(){c.result=j};e.onerror=n()},[a],"readwrite")};o.get=function(a,b){if(!ub(this.a,a))throw Error("Store: "+a+" not exist.");return Z(this,function(c){var d=c.objectStore(a).get(b);d.onsuccess=function(a){c.result=a.target.result};d.onerror=n()},[a],"readonly")};
o.q=function(a){var b=a.value,c=a.c,d=a.a||"default_text_store";c||(c=this.a[a.a].keyPath);return Z(this,function(e){var f=e.objectStore(d).index(c),g;g="";if(a.b=="st"){g=b.substring(0,b.length-1)+String.fromCharCode(b.charCodeAt(b.length-1)+1);g=Qb.bound(b,g,m,j)}else g=Qb.only(b);f=f.openCursor(g);f.onsuccess=function(a){if(a=a.target.result){if(!e.result)e.result=[];e.result.push(a.value);a["continue"]()}};f.onerror=n()},[d],"readwrite")};
o.clear=function(a){if(a)return Sb(this,a);var a=[],b;for(b in this.a)a.push(Sb(this,b));return Xa(new N(a))};o.p=function(){var a=new K;if(w(Y.deleteDatabase))Y.deleteDatabase(this.b);else return this.clear();return a};function Sb(a,b){return Z(a,function(a){var d=a.objectStore(b).clear();d.onsuccess=function(){a.result=j};d.onerror=n()},[b],"readwrite")}
o.count=function(a){return Z(this,function(b){var c=b.objectStore(a).count();c.onsuccess=function(a){b.result=a.target.result};c.onerror=n()},[a],"readonly")};function Tb(a,b){this.b=b[b.length-1];this.a={};for(var c in this.b)this.a[c]={}}o=Tb.prototype;o.put=function(a,b){this.a[a][b[this.b[a].keyPath]]=b;return M(j)};o.get=function(a,b){var c=this.b[a].keyPath,d;for(d in this.a[a]){var e=this.a[a][d];if(e[c]===b)return M(e)}return Wa(i)};o.clear=function(a){if(r(a))this.a[a]={};else for(var b in this.a)this.a[b]={};return M(j)};o.count=function(a){var a=a||"default_text_store",b=new K,c=0,d;for(d in this.a[a])c++;b.d(c);return b};o.q=function(){return Wa(j)};
o.p=function(){return this.clear()};function Ub(a,b){this.b=a;this.f=b;this.a=b[b.length-1];this.db=p.openDatabase(this.b,"",this.b,this.a.size);if(this.db.version!=this.a.version){for(var c=this,d=function(){Ib(c.i,"Creating tables OK.")},e=function(){W(c.i,"Error creating tables")},f=[],g=0;g<this.a.j.length;g++)f.push(Vb(this.a.j[g]));this.db.transaction(function(a){Ib(c.i,"Creating tables "+f.join("\n"));a.executeSql(f.join("\n"),[],d,e)})}}o=Ub.prototype;o.i=Lb("ydn.db.WebSql");
function Vb(a){var b="CREATE TABLE IF NOT EXISTS "+E(a.name)+" ("+E(a.keyPath)+" TEXT UNIQUE PRIMARY KEY";Ma(a.a,function(a){return"_default_"==a.name})||a.a.push(new ob("_default_",i,i));for(var c=0;c<a.a.length;c++)var d=a.a[c],b=b+(", "+d.name+(d.unique?" UNIQUE ":" ")+d.type);return b+");"}
o.put=function(a,b){function c(a,b){W(h.i,"put error: "+b);e.e(i)}function d(){e.d(j)}var e=new K,f=O(this.a,a);if(!f)return W(this.i,"Table "+a+" not found."),e.e(i),e;var g=ca(b)?b:[b],h=this;h.db.transaction(function(a){for(var b,e,h,B=0;B<g.length;B++){var x=B==g.length-1;b=f;var ha=g[B],Ra=[E(b.keyPath)];h=[Za(ha,b.b)];e=["?"];for(var C=0;C<b.a.length;C++)if("_default_"!=b.a[C].name){var v=ha[b.a[C].name];r(v)&&("INTEGER"==b.a[C].type?"number"==typeof v||(v=parseInt(v,10)):"REAL"==b.a[C].type?
"number"==typeof v||(v=parseFloat(v)):u(v)||(v=$a(v)),h.push(v),e.push("?"),Ra.push(E(b.a[C].name)))}C={};v=i;for(v in ha)ha.hasOwnProperty(v)&&!rb(b,v)&&(C[v]=ha[v]);h.push($a(C));e.push("?");Ra.push("_default_");b=Ra;e="INSERT OR REPLACE INTO "+E(f.name)+" ("+b.join(", ")+") VALUES ("+e.join(", ")+");";a.executeSql(e,h,x?d:i,x?c:i)}});return e};
function Wb(a,b){for(var c=ab(b._default_),d=c,e=b[a.keyPath],f=0;f<a.b.length;f++){var g=a.b[f];if(f==a.b.length-1){d[g]=e;break}r(d[g])||(d[g]={});d=d[g]}for(d=0;d<a.a.length;d++)e=a.a[d],"_default_"!=e.name&&(f=b[e.name],r(f)&&("INTEGER"==e.type?f=parseInt(f,10):"REAL"==e.type&&(f=parseFloat(f)),c[e.name]=f));return c}
o.get=function(a,b){function c(a,b){W(g.i,"Sqlite error: "+b);e.e(i)}function d(a,b){if(0<b.rows.length){var c=b.rows.item(0);e.d(Wb(f,c))}else e.d(i)}var e=new K,f=O(this.a,a);f||(W(this.i,"Table "+a+" not found."),e.e(i));var g=this,h="SELECT * FROM "+E(f.name)+" WHERE "+E(f.keyPath)+" = "+E(b)+";";this.db.transaction(function(a){a.executeSql(h,[],d,c)});return e};
o.q=function(a){function b(a,b){W(e.i,"Sqlite error: "+b);d.e(i)}function c(a,b){for(var c=[],e=0;e<b.rows.length;e++){var g=b.rows.item(e);c.push(Wb(f,g))}d.d(c)}var d=new K,e=this,f=O(this.a,a.a),g=a.c||f.keyPath,h="SELECT * FROM "+E(f.name)+" WHERE ",h="st"==a.b?h+("("+g+" LIKE ?)"):h+("("+E(g)+" = ?)");this.db.transaction(function(d){d.executeSql(h,[a.value+"%"],c,b)});return d};
function Xb(a,b){function c(b,c){W(a.i,"Sqlite error: "+c);e.e(i)}function d(){e.d(j)}var e=new K,f="DELETE FROM  "+b;a.db.transaction(function(a){a.executeSql(f,[],d,c)});return e}o.clear=function(a){if(a)return Xb(this,a);var a=[],b;for(b in this.a)a.push(Xb(this,b));return Xa(new N(a))};
o.count=function(a){function b(a,b){W(e.i,"count error: "+b);d.e(i)}function c(a,b){var c=b.rows.item(0);d.d(c["COUNT(*)"])}var d=new K,e=this,f="SELECT COUNT(*) FROM "+(a||"default_text_store");this.db.transaction(function(a){a.executeSql(f,[],c,b)});return d};
o.p=function(){function a(a,b){W(d.i,"Delete TABLE: "+b);c.e(i)}function b(){c.d(j);W(d.i,"Deleted database: "+d.b)}var c=new K,d=this;this.db.transaction(function(c){for(var f="",g=0;g<d.a.j.length;g++)f=f+"DROP TABLE "+d.a.j[g].name+";";c.executeSql(f,[],b,a)});return c};/*
 Copyright 2012 YDN Authors. All Rights Reserved.
*/
function $(a,b){this.b=new K;r(a)&&this.g(a);r(b)&&this.m(b)}$.prototype.v=function(){if(!this.c())throw Error("Database not initialized.");var a=this.f.map(function(a){return a.toJSON()});return{o:this.o,f:a}};A("ydn.db.Storage.prototype.getConfig",$.prototype.v);$.prototype.g=function(a){if(this.a)throw Error("DB already initialized");this.o=a.replace(/[@|\.|\s]/g,"");Yb(this);return this.o};A("ydn.db.Storage.prototype.setDbName",$.prototype.g);
$.prototype.w=function(a){this.f=this.f||[];this.f.push(a);Yb(this)};A("ydn.db.Storage.prototype.setLastSchema",$.prototype.w);$.prototype.m=function(a){this.f=a||[];Yb(this)};A("ydn.db.Storage.prototype.setSchemas",$.prototype.m);
function Yb(a){if(r(a.o)&&r(a.f)){var b=a.f[a.f.length-1];!/^[\s\xa0]*$/.test("default_text_store")&&!ub(b,"default_text_store")&&b.j.push(new pb("default_text_store"));Y?a.a=new Nb(a.o,a.f):w(p.openDatabase)?a.a=new Ub(a.o,a.f):window.localStorage?a.a=new Ya(a.o,a.f):a.a=new Tb(0,a.f);a.b.n&&(a.b=new K);a.b.d(a.a)}}$.prototype.c=function(){return!!this.a};A("ydn.db.Storage.prototype.isReady",$.prototype.c);$.prototype.setItem=function(a,b){return this.put("default_text_store",{id:a,value:b})};
A("ydn.db.Storage.prototype.setItem",$.prototype.setItem);$.prototype.put=function(a,b){if(this.a)return this.a.put(a,b);var c=new K;this.b.k(function(d){L(d.put(a,b),c)});return c};A("ydn.db.Storage.prototype.put",$.prototype.put);$.prototype.getItem=function(a){var a=this.get("default_text_store",a),b=new K;a.k(function(a){b.d(a.value)});a.B(function(a){b.e(a)});return b};A("ydn.db.Storage.prototype.getItem",$.prototype.getItem);
$.prototype.get=function(a,b){if(this.a)return this.a.get(a,b);var c=new K;this.b.k(function(d){L(d.get(a,b),c)});return c};A("ydn.db.Storage.prototype.get",$.prototype.get);$.prototype.clear=function(a){if(this.a)return this.a.clear(a);var b=new K;this.b.k(function(c){L(c.clear(a),b)});return b};A("ydn.db.Storage.prototype.clear",$.prototype.clear);$.prototype.p=function(){if(this.a)return this.a.p();var a=new K;this.b.k(function(b){L(b.p(),a)});return a};A("ydn.db.Storage.prototype.delete",$.prototype.p);
$.prototype.count=function(a){if(this.a)return this.a.count(a);var b=new K;this.b.k(function(c){L(c.count(a),b)});return b};A("ydn.db.Storage.prototype.count",$.prototype.count);$.prototype.q=function(a){if(this.a)return this.a.q(a);var b=new K;this.b.k(function(c){L(c.q(a),b)});return b};A("ydn.db.Storage.prototype.fetch",$.prototype.q);A("ydn.db.Storage",$);A("ydn.db.DatabaseSchema",sb);A("ydn.db.DatabaseSchema.fromJSON",tb);K.prototype.success=K.prototype.k;K.prototype.error=K.prototype.B;})();
